package pe.edu.ulima.ufound.model;

public enum UbicacionCampus {
    A1("A1"),
    A2("A2"),
    B("B"),
    C("C"),
    D1("D1"),
    D2("D2"),
    D3("D3"),
    E1("E1"),
    E2("E2"),
    E3("E3"),
    F1("F1"),
    F2("F2"),
    G("G"),
    H("H"),
    I1("I1"),
    I2("I2"),
    J("J"),
    K("K"),
    L1("L1"),
    L2("L2"),
    L3("L3"),
    N("N"),
    O1("O1"),
    O2("O2"),
    P("P"),
    AULAS("Aulas"),
    LABORATORIOS("Laboratorios"),
    TALLERES("Talleres"),
    SALAS_ESTUDIO("Salas de estudio"),
    ESPACIOS_PREGRADO("Espacios de pregrado"),
    ESPACIOS_POSGRADO("Espacios de posgrado"),
    EDUCACION_EJECUTIVA("Educacion Ejecutiva"),
    CENTRO_IDIOMAS("Centro de Idiomas"),
    BIBLIOTECA("Biblioteca"),
    SALA_LECTURA("Sala de lectura"),
    SALA_LECTURA_SILENCIOSA("Sala de lectura silenciosa"),
    MODULOS_BIBLIOTECA("Modulos de atencion de biblioteca"),
    ZONA_ESTANTERIAS("Zona de estanterias"),
    ZONA_CONSULTA("Zona de consulta"),
    ZONA_TESIS("Zona de trabajos de investigacion / tesis"),
    CAFETERIA_EDIFICIO_O("Cafeteria Edificio O"),
    CAFETERIA_EDIFICIO_F2("Cafeteria Edificio F2"),
    CAFETERIA_PARQUE_CRUZ_DEL_SUR("Cafeteria Parque Cruz del Sur"),
    CONCESIONARIOS("Concesionarios"),
    RESTAURANTES_CAMPUS("Restaurantes del campus"),
    QUIOSCOS("Quioscos"),
    AUDITORIO_G("Auditorio G"),
    AUDITORIO_I2("Auditorio I2"),
    AUDITORIO_O("Auditorio O"),
    AUDITORIO_ZUM("Auditorio ZUM"),
    AULA_MAGNA_A("Aula Magna A"),
    AULA_MAGNA_B("Aula Magna B"),
    AULA_MAGNA_O1("Aula Magna O1"),
    AULA_MAGNA_O2("Aula Magna O2"),
    AULA_MAGNA_O3("Aula Magna O3"),
    AULA_MAGNA_O4("Aula Magna O4"),
    TEATRO_CENTRO_CULTURAL("Teatro del Centro Cultural"),
    GALERIA_ULIMA("Galeria Ulima"),
    CAPILLA_D3("Capilla Edificio D3"),
    CAJEROS_J("Cajeros automaticos Edificio J"),
    TIENDA_ULIMA_A1("Tienda Ulima Edificio A1"),
    LIBUN_A1("Libun Edificio A1"),
    OFICINA_OBJETOS_PERDIDOS_A1_303("Oficina de Objetos Perdidos A1-303"),
    ESTACIONAMIENTO_A1("Estacionamiento A1"),
    ESTACIONAMIENTO_H("Estacionamiento H"),
    ESTACIONAMIENTO_N("Estacionamiento N"),
    ESTACIONAMIENTO_CRUZ_DEL_SUR("Estacionamiento Cruz del Sur"),
    GIMNASIO_F1("Gimnasio Edificio F1"),
    PLAZA_RECREATIVA("Plaza Recreativa"),
    PASILLOS("Pasillos"),
    ESCALERAS("Escaleras"),
    ASCENSORES("Ascensores"),
    BANOS("Banos"),
    PATIOS("Patios"),
    PLAZAS("Plazas"),
    AREAS_DESCANSO("Areas de descanso"),
    AREAS_VERDES("Areas verdes"),
    ENTRADAS_SALIDAS("Entradas y salidas del campus"),
    OTRO("Otros"),
    EDIFICIO_A("Edificio A"),
    EDIFICIO_B("Edificio B"),
    EDIFICIO_C("Edificio C"),
    EDIFICIO_D("Edificio D"),
    EDIFICIO_E("Edificio E"),
    PABELLON_CENTRAL("Pabellon Central"),
    CAFETERIA("Cafeteria"),
    AULA_MAGNA("Aula Magna"),
    ESTACIONAMIENTO("Estacionamiento");

    private final String etiqueta;

    UbicacionCampus(String etiqueta) {
        this.etiqueta = etiqueta;
    }

    public String getEtiqueta() {
        return etiqueta;
    }
}
